### PR TITLE
[Perpetual]: add stop loss price

### PR DESCRIPTION
**Pull request by cryptokage1996**
Add message to update the stop loss of a given position.

### CODE REVIEW

**Comment by cosmic-vagabond** [comment]
@cryptokage1996 can you provide test results?

**Comment by amityadav0** [comment]
I see we are only setting stop loss value, shouldn't we add logic for stop loss trigger ? when this will trigger ?
- When custody amount hits stop loss or is there any other variable ?

**Review by amityadav0 — APPROVED** [review]
LGTM

**Comment by cosmic-vagabond** [comment]
@cryptokage1996 @amityadav0 I agree without the ABCI logic for trigger the stop loss (closing of the position) it will be useful at all, is there any reason we are ommiting that part?

**Comment by cosmic-vagabond** [comment]
@cryptokage1996 the software upgrade test is failing due to a module migration error see here https://github.com/elys-network/elys/actions/runs/10771967355/job/29870663829?pr=759

**Comment by avkr003** [comment]
@cryptokage1996  Multiple migrations are happening here, and your code is skipping one version.
`err := cfg.RegisterMigration(types.ModuleName, 5, m.V6Migration)
	if err != nil {
		panic(err)
	}`
Do not remove this. And add your code next to it:
`err := cfg.RegisterMigration(types.ModuleName, 6, m.V7Migration)
	if err != nil {
		panic(err)
	}
	`	
	Or,
	You can add code in `m.V7Migration` to `m.V6Migration` at the end and remove `.V7Migration` and consensus version back to 6

image

**Pull request merged**
