### PR TITLE
adding autocli options for parameter module

### PR DESCRIPTION
**Pull request by avkr003**

### CODE REVIEW

**Comment by avkr003** [comment]
@amityadav0 https://docs.cosmos.network/main/learn/advanced/autocli

**Comment by amityadav0** [comment]
@avkr003 got it, thanks. my question was why do we need it ? for testing ? for FE interfaces ? I'm just curious

**Comment by amityadav0** [comment]
is it ignite substitute ?

**Comment by avkr003** [comment]
@amityadav0 No, ignite is a different tool. This is not a tool. It just writes your cli queries and txs for you, so you don't have to write them yourself.
I haven't figured out how to use ignite with v0.50 yet as it still hasn't been needed yet.

**Comment by avkr003** [comment]
To add CLI cmd automatically, you will need to add a file called autocli.go I have written the code for assetprofile, stablestake and parameter module as examples. Can look for more examples in cosmos SDK repository.
This reduces our effort of writing cli queries but also to write test cases for it.
If we need a custom query that autocli cannot provide then we can still write the custom query for it and autocli will enhance it overall.

**Review by cosmic-vagabond — APPROVED** [review]

**Pull request merged**
