### PR TITLE
docs: add leverage lp module specs

### PR DESCRIPTION
**Pull request by cosmic-vagabond**
### What has Changed?

Leverage LP module specifications

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/elys-network/elys/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/elys-network/elys/blob/main/docs/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/elys-network/elys/blob/main/CONTRIBUTING.md#testing)
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### Deployment Notes

Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be evaluated in a deployed environment.

### Screenshots and Videos

Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos can be highly beneficial in demonstrating the process.

### CODE REVIEW

**Review by amityadav0 — COMMENTED** [review]
I was wondering if we can add the equations/mechanism for leverage open, close. for example: similar to how in amm x*y = k should be maintained. Is it possible here ?

**Comment by cosmic-vagabond** [comment]
> I was wondering if we can add the equations/mechanism for leverage open, close. for example: similar to how in amm x*y = k should be maintained. Is it possible here ?

@amityadav0 Good call out. The LeverageLP module operates in conjunction with two other modules: StableStake and AMM.

* In this system, some participants will bond their USDC tokens to the StableStake module, while others will use LeverageLP to borrow those bonded tokens to enhance their liquidity position in the AMM pool. This results in a debt that is recorded within the StableStake module.
* Therefore, the AMM module is utilized by participants opening a Leverage LP position to join a pool with the leveraged amount of USDC (borrowed from StableStake).

The crucial equation that helps maintain balance is:

$\text{Pool Health} = \frac{\text{Total Shares} - \text{Leveraged LP Amount}}{\text{Total Shares}}$

We ensure that Pool Health does not fall below the Safety Factor threshold, which is set at 10%.

As more leveraged liquidity is added to the pool, the Pool Health decreases, putting the underlying liquidity pool at risk of having the leveraged position liquidated.

Another important concept is the liquidation mechanism. If the position health falls below the safety factor (10%), the leverage LP position is liquidated.

$\text{Position Health} = \frac{\text{Position Value}}{\text{Borrowed Amount} + \text{Interest Staked} + \text{Interest Paid}}$

Let me update the documentation in order to include those concepts.

**Comment by cosmic-vagabond** [comment]
> I was wondering if we can add the equations/mechanism for leverage open, close. for example: similar to how in amm x*y = k should be maintained. Is it possible here ?

@amityadav0 you can find the new section `mechanism` here https://github.com/elys-network/elys/pull/545/commits/bc851ac512e366cbe39741768c558475c016f1f3

**Comment by amityadav0** [comment]
thanks!

**Comment by jelysn** [comment]
Leveragelp and Masterchef docs are coming in https://github.com/elys-network/elys/pull/544 and I recommend to close this PR or update the base to `post_v32_fix`

**Comment by cosmic-vagabond** [comment]
duplicated https://github.com/elys-network/elys/pull/544

**Pull request closed without merging**
